spring.application.name=keepsake
spring.datasource.url=jdbc:postgresql://localhost:5433/keepsake
spring.datasource.username=keepsake
spring.datasource.password=keepsake
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=60MB
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax

keepsake.storage.local-root=./data/uploads
keepsake.security.seed-admin-username=admin
keepsake.security.seed-admin-password=admin
